// src/components/MainCanvas.tsx
import React from "react";
import { TankController } from "../controllers/TankController";
import { dimensions } from "../utils/utils";
import { BulletController } from "../controllers/BulletController";
import { ImgCache } from "../models/Cache";
import { Box } from "@mui/material";
import TankComponent from "./Tank";
import ScopeComponent from "./Scope";
import { GameMap } from "../models/Map";
import MapComponent from "./Map";
import { GameController } from "../controllers/GameController";
import CannonComponent from "./Cannon";

export default function MainCanvas() {
    const [thisWindow, setThisWindow] = React.useState<dimensions>({
        height: 0,
        width: 0
    });
    const ContainerRef = React.useRef(null);

    const [render, rerender] = React.useState(false);

    TankController.triggerComponentRender = () => { rerender(!render) };

    React.useEffect(() => {
        GameController.addToGameLoop(TankController.Move);
        GameController.addToGameLoop(keyboardHandler);
    }, [])

    React.useEffect(() => {
        setThisWindow({
            height: window.innerHeight,
            width: window.innerWidth
        })

        return () => { }
    }, [render])


    const keyboardHandler = () => {
        document.addEventListener('keypress', (e) => TankController.addKey(e.key), { once: true });
        document.addEventListener('keyup', (e) => TankController.removeKey(e.key), { once: true });
        document.addEventListener('mousemove', (e) => TankController.scopePlacement(e), { once: true });
    }

    return (
        <Box style={{ border: "1px solid black", height: thisWindow.height, width: thisWindow.width }}
            ref={ContainerRef}
        >
            
            <TankComponent
                heigth={100}
                width={100}
                position={TankController.tank.position}
                rotation={TankController.tank.rotation}
            >
                <CannonComponent
                    heigth={50}
                    width={150}
                    rotation={TankController.cannonRotation}
                />
            </TankComponent>


            <ScopeComponent
                heigth={50}
                width={50}

            />

            {/* <MapComponent width={0} heigth={0} /> */}



        </Box>


    )
}

// src/app/components/mainCanvas/mainCanvas.component.ts
import { Component, HostListener, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { dimensions } from '../../utils/utils';
import { BulletController } from "../../controllers/BulletController";
import { TankController } from "../../controllers/TankController";
import { ScopeComponent } from "../scope/scope.component";
import { TankComponent } from "../tank/tank.component";
import { BulletComponent } from "../bullet/bullet.component";
import { MapComponent } from "../map/map.component";
import { GameMap } from "../../models/Map";

@Component({
    selector: 'app-mainCanvas',
    standalone: true,
    templateUrl: './mainCanvas.component.html',
    styleUrls: ['./mainCanvas.component.css'],
    imports: [
        CommonModule,
        ScopeComponent,
        TankComponent,
        BulletComponent,
        MapComponent
    ]
})
export class MainCanvasComponent implements OnInit {
    IGameMap = GameMap;
    ITankController = TankController;

    currentWindow: dimensions = {
        height: 0,
        width: 0
    }

    constructor() { }

    @HostListener('mousemove', ['$event'])
    onMouseMove(e: MouseEvent){
        TankController.scopePlacement(e);
    }

    @HostListener('click', ['$event'])
    onClick(e: Event){
        BulletController.shoot();
    }

    setDivStyles(){
        return {
            "border": "1px solid black", 
            "height": this.currentWindow.height, 
            "width": this.currentWindow.width
        }
    }

    ngOnInit() {
        this.currentWindow = {
            height: window.innerHeight,
            width: window.innerWidth
        }
    }

}

<div [ngStyle]="setDivStyles()">
  <!-- <gamebar></gamebar> -->
  <br><br><br><br>
  <app-map></app-map>
  <!-- <app-cpu></app-cpu> -->
  <!-- <app-tank></app-tank> -->
  <!-- <app-bullet></app-bullet> -->
  <app-scope></app-scope>
  <ng-content #container></ng-content>
</div>
