// src/components/BulletComponent.tsx
import React from "react";
import { GameController } from "../controllers/GameController";
import { BulletController } from "../controllers/BulletController";
import { TankController } from "../controllers/TankController";


interface BulletProps {
    width: number;
    heigth: number;
}

export default function BulletComponent(props:BulletProps){
    
    const [position, setPosition] = React.useState(BulletController.bullet.position);

    const [render, triggerRender] = React.useState(false);

    BulletController.triggerComponentRender = ()=>{triggerRender(!render)}

    const bulletPosition = () => setPosition(BulletController.bullet.position)

    React.useEffect(() => {
        //GameController.addToGameLoop(bulletPosition);
        setInterval(()=>{
            bulletPosition
        }, 24)
        console.log("renderizado");
    }, [])


    return(<>
        <img src="/bullet.png"
        style={{
            position: 'absolute',
            zIndex: 60,
            width: props.width,
            height: props.heigth, 
            top: position.y,
            left: position.x,
            rotate: `${BulletController.bullet.rotation}rad`}}
            />
            {`jamon X: ${position.x} jamon y: ${position.y}`}</>
    )
}

// src/app/components/bullet/bullet.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameController } from "../../controllers/GameController";
import { BulletController } from "../../controllers/BulletController";
import { Bullet } from '../../models/Bullet';
import { TankController } from '../../controllers/TankController';
import { CPUController } from '../../controllers/CPUController';

@Component({
    selector: 'app-bullet',
    standalone: true,
    templateUrl: './bullet.component.html',
    styleUrls: ['./bullet.component.scss'],
    imports: [CommonModule]
})
export class BulletComponent implements OnInit {
    @Input("type") type: "player" | "CPU";

    bullet : Bullet;

    constructor() {
        this.bullet = new Bullet();

        
     }

    ngOnInit() {
        console.log(this.type);
        
        if (this.type == "player") {
            TankController.bullets.push(this.bullet);
        } else {
            CPUController.bullet = this.bullet;
        }
    }

    setStyles() {
        return {
            "position": 'absolute',
            "zIndex": 60,
            "width": "30px",
            "height": "20px",
            "top": `${this.bullet.position.y}px`,
            "left": `${this.bullet.position.x}px`,
            "rotate": `${this.bullet.rotation}rad`
        }
    }

}

<div #self>
    <img src="/assets/images/bullet.png" alt="" [ngStyle]="setStyles()">
</div>
