// src/components/Scope.tsx
import { Box } from "@mui/material";
import { Position } from "../models/Tank";
import React, { useState } from "react";
import { TankController } from "../controllers/TankController";


interface ScopeComponentProps{
    width: number;
    heigth: number;
}

export default function ScopeComponent(props:ScopeComponentProps){

    // TODO: El scope no se mueve por el trggercomonentrerender que ya no esta en mainCanvas

    const [position, setPosition] = React.useState(TankController.scopePos);



    React.useEffect(() => {
        setInterval(() => {
            setPosition(TankController.scopePos);
        }, 24);
    }, [])

    // React.useEffect(() => {
    //     console.log("hamaica");
        
    //     return (()=>{})
    // }, [position])

    return(
            <>
            <img src="/mira.png"  
            style={{
                position: 'absolute',
                zIndex: 100,
                width: props.width,
                height: props.heigth, 
                top: position.y - (props.width /2),
                left: position.x - (props.heigth /2)}}
                />

                {`Scope${TankController.scopePos.x}, ${TankController.scopePos.y}`}<br/>
                {`Tanke${TankController.tank.position.x}, ${TankController.tank.position.y}`}<br/>
                {`Cannon ${TankController.cannonRotation} grados`}
                </>
    )
}

// src/app/components/scope/scope.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TankController } from "../../controllers/TankController";
import { GameController } from "../../controllers/GameController";

interface ScopeComponentProps {
    width: number;
    heigth: number;
}

@Component({
    selector: 'app-scope',
    standalone: true,
    templateUrl: './scope.component.html',
    styleUrls: ['./scope.component.css'],
    imports: [CommonModule]
})
export class ScopeComponent implements OnInit {
    @Input() props: ScopeComponentProps;

    ITankController = TankController;
    IGameController = GameController;

    position = TankController.scopePos;

    constructor() {

    }

    setStyles() {
        return {
            "position": 'absolute',
            "pointerEvents": "none",
            "zIndex": 100,
            "width": this.props.width,
            "height": this.props.heigth,
            "top": this.position.y - (this.props.width / 2),
            "left": this.position.x - (this.props.heigth / 2)
        }
    }

    scopePosition() {
        this.position = TankController.scopePos;
    }


    ngOnInit() {
        GameController.addToGameLoop(this.scopePosition);
        console.log("ScopeComponent rendered");
    }

}

<div>
            <img src="/mira.png" id="scope" [ngStyle]="setStyles()" />

              Scope{{ITankController.scopePos.x}}, {{ITankController.scopePos.y}}<br/>
              Tanke{{ITankController.tank.position.x}}, {{ITankController.tank.position.y}}<br/>
              Cannon{{ITankController.cannonRotation}} grados
</div>
