// src/app/components/bullet/bullet.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameController } from "../../controllers/GameController";
import { BulletController } from "../../controllers/BulletController";
import { Bullet } from '../../models/Bullet';
import { TankController } from '../../controllers/TankController';
import { CPUController } from '../../controllers/CPUController';

@Component({
    selector: 'app-bullet',
    standalone: true,
    templateUrl: './bullet.component.html',
    styleUrls: ['./bullet.component.scss'],
    imports: [CommonModule]
})
export class BulletComponent implements OnInit {
    @Input("type") type: "player" | "CPU";

    bullet : Bullet;

    constructor() {
        this.bullet = new Bullet();

        
     }

    ngOnInit() {
        console.log(this.type);
        
        if (this.type == "player") {
            TankController.bullets.push(this.bullet);
        } else {
            CPUController.bullet = this.bullet;
        }
    }

    setStyles() {
        return {
            "position": 'absolute',
            "zIndex": 60,
            "width": "30px",
            "height": "20px",
            "top": `${this.bullet.position.y}px`,
            "left": `${this.bullet.position.x}px`,
            "rotate": `${this.bullet.rotation}rad`
        }
    }

}

<div #self>
    <img src="/assets/images/bullet.png" alt="" [ngStyle]="setStyles()">
</div>

// src/components/Bullet.tsx
import { Box } from "@mui/material";
import { Position } from "../models/Tank";
import React from "react";
import { GameController } from "../controllers/GameController";
import { TankController } from "../controllers/TankController";
import { Bullet } from "../models/Bullet";
import { BulletController } from "../controllers/BulletController";


interface BulletProps {
    width: number;
    heigth: number;
    position: Position;
    rotation: number;
    render?: boolean;

}

export default function BulletComponent(props:BulletProps){
    
    const [position, setPosition] = React.useState(TankController.scopePos);


    React.useEffect(() => {
        setInterval(() => {
            setPosition(TankController.scopePos);
            // console.log(BulletController.bullet.position);
            
        }, 24);
    }, [])


    return(
        <img src="/bullet.png"  
        style={{
            position: 'absolute',
            zIndex: 60,
            width: props.width,
            height: props.heigth, 
            top: props.position.y,
            left: props.position.x,
            rotate: `${BulletController.bullet.rotation}rad`}}
            />
    )
}
