// src/app/components/cannon/cannon.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { GameController } from "../../controllers/GameController";
import { TankController } from "../../controllers/TankController";

interface CannonComponentProps {
    width: number;
    heigth: number;
    rotation: number;
}

@Component({
    selector: 'app-cannon',
    templateUrl: './cannon.component.html',
    standalone: true,
    styleUrls: ['./cannon.component.css'],
    imports: [CommonModule]
})
export class CannonComponent implements OnInit {
    @Input() props: CannonComponentProps;

    ITankController = TankController;
    IGameController = GameController;

    rotation = TankController.scopePos;

    constructor() { }

    setStyles() {
        return {
            'position': 'relative',
            'zIndex': 55,
            'width': this.props.width,
            'height': this.props.heigth,
            'rotate': `${TankController.cannonRotation}rad`
        };
    }

    cannonRotation() {
        this.rotation = TankController.scopePos;
    }

    ngOnInit() {
        GameController.addToGameLoop(this.cannonRotation)
    }

}

<div>
  <img src="/tanky-top-1.png" [ngStyle]="setStyles()" alt="">
</div>

// src/components/Cannon.tsx
import { Box } from "@mui/material";
import { Position } from "../models/Tank";
import React from "react";
import { TankController } from "../controllers/TankController";


interface TankComponentProps{
    width: number;
    heigth: number;
    rotation: number;
    render?: boolean;
    // children: JSX.Element
}

export default function CannonComponent(props:TankComponentProps){

    const [rotation, setRotation] = React.useState(TankController.scopePos);

    React.useEffect(() => {
        setInterval(() => {
            setRotation(TankController.scopePos);
        }, 24);
    }, [])


    return(
        <Box>

            <img src="/tanky-top-1.png"  
            style={{
                position: 'relative',
                zIndex: 55,
                width: props.width,
                height: props.heigth, 
                rotate: `${TankController.cannonRotation}rad`}}
                />
                
        </Box>
    )
}
