// src/app/components/tank/tank.component.ts
import { Component, OnInit, Input, HostListener, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CannonComponent } from "../cannon/cannon.component";
import { GameController } from "../../controllers/GameController";
import { TankController } from "../../controllers/TankController";
import { Position } from "../../models/Tank";

@Component({
    selector: 'app-tank',
    standalone: true,
    templateUrl: './tank.component.html',
    styleUrls: ['./tank.component.css'],
    imports: [ CommonModule, CannonComponent ]
})
export class TankComponent implements OnInit {
    IGameController = GameController;
    ITankController = TankController;

    constructor() { }

    ngOnInit() {
        GameController.addToGameLoop(TankController.Move);
    }

    @HostListener('keypress', ['$event'])
    onKeyPress(e: KeyboardEvent){
        TankController.addKey(e.key)
    }

    @HostListener('keyup', ['$event'])
    onKeyUp(e: KeyboardEvent){
        TankController.removeKey(e.key)
    }

    setDivStyles(){
        return {
            "position": 'absolute',
            "width": 45,
            "height": 45,
            "top": TankController.tank.position.x,
            "left": TankController.tank.position.y,
            "rotate": `${TankController.tank.rotation}deg`,
            "display": 'flex',
            "justifyContent": 'center',
            "alignItems": 'center',
            "border": '1px solid green'
        }
    }

    setImgStyles(){
        return {
            "position": 'absolute',
            "width": 45,
            "height": 45,
            "zIndex": 50,
            "rotate": `${TankController.tank.rotation}deg`,
            "border": '1px solid red'
        }
    }

}

<div [ngStyle]="setDivStyles()">
  <app-cannon [heigth]="22.5" [width]="67.5"></app-cannon>
  <img
    src="/assets/images/tanks/tanky-bot.png"
    [ngStyle]="setImgStyles()"
    alt=""
  />
</div>

// src/components/Tank.tsx
import { Box } from "@mui/material";
import { Position } from "../models/Tank";
import React from "react";
import { GameController } from "../controllers/GameController";
import { TankController } from "../controllers/TankController";


interface TankComponentProps {
    width: number;
    heigth: number;
    position: Position;
    rotation: number;
    children: JSX.Element;
}

export default function TankComponent(props: TankComponentProps) {

    const [render, rerender] = React.useState(false);

    TankController.triggerComponentRender = () => { rerender(!render) };

    React.useEffect(() => {
        GameController.addToGameLoop(TankController.Move);
        GameController.addToGameLoop(keyboardHandler);
    }, [])

    React.useEffect(() => {

        return () => { }
    }, [render])


    const keyboardHandler = () => {
        document.addEventListener('keypress', (e) => TankController.addKey(e.key), { once: true });
        document.addEventListener('keyup', (e) => TankController.removeKey(e.key), { once: true });
    }
    React.useEffect(() => {

    }, [props])

    return (

        <Box sx={{
            position: 'absolute',
            width: props.width,
            height: props.heigth,
            top: props.position.x,
            left: props.position.y,
            rotate: `${props.rotation}deg`,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            border: '1px solid green'
        }}>
            <img
                src="/tanky-bot.png" 
                style={{
                    position: 'absolute',
                    width: props.width,
                    height: props.heigth,
                    zIndex: 50,
                    rotate: `${props.rotation}deg`,

                    border: '1px solid red'
                }} />
            {React.cloneElement(props.children, {render: render})}
        </Box>

    )
}
